//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketPlace.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankCard
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string CVV { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BankId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual Bank Bank { get; set; }
        public virtual User User { get; set; }
    }
}
